@microservicesSales_HostAddress = http://localhost:8080
@productId = f271ad2e-2d80-4bbf-a56e-a4e23143b8fb


###new product
POST {{microservicesSales_HostAddress}}/api/Product/CreateProduct
Content-Type: application/json

{
  "name": "Laptop TOM",
  "price": 1500,
  "initialStock":10
}


###new product negative
POST {{microservicesSales_HostAddress}}/api/Product/CreateProduct
Content-Type: application/json

{
  "name": "Laptop TOM",
  "price": -56,
  "initialStock":0
}

### Get all products
GET {{microservicesSales_HostAddress}}/api/Product/GetAllProducts
Accept: application/json

### Get product by id
GET {{microservicesSales_HostAddress}}/api/Product/GetProductById/{{productId}}
Accept: application/json

### Update product
PATCH {{microservicesSales_HostAddress}}/api/Product/UpdateProduct/{{productId}}
Content-Type: application/json

{
  "name": "Laptop Dell XPS",
  "price": 1299.99
}

### Delete product
DELETE {{microservicesSales_HostAddress}}/api/Product/DeleteProduct/{{productId}}

### Adjust stock (increase)
PATCH {{microservicesSales_HostAddress}}/api/Product/AdjustStock/{{productId}}
Content-Type: application/json

{
  "quantity": 5
}

### Reduce stock
PATCH {{microservicesSales_HostAddress}}/api/Product/ReduceStock/{{productId}}
Content-Type: application/json

{
  "quantity": 2
}


### Create sale - success example
POST {{microservicesSales_HostAddress}}/api/Sales/CreateSale
Content-Type: application/json

{
  "items": [
    { "productId": "23ef5822-30e4-4413-82a9-246775eaaa77", "quantity": 2 },
    { "productId": "a2649c6f-a73e-4982-9764-8b9d5d8d48a5", "quantity": 1 }
  ]
}

### Get sale by id (route style)
GET {{microservicesSales_HostAddress}}/api/Sales/GetSale/0916c018-df31-4210-b69f-c5fd53db5034
Accept: application/json

